### ISSUE TITLE
About Section (Our Story)

### ISSUE THREAD

**Issue by terry212** [Codeinwp/llorix-one-lite#103]
In the about section, it does not allow for me to space out the words as specified. For example, I can write the content and use the ENTER key to create a break in a paragraph, but when the changes are saved; it does not appear the exact way it was written in the textarea box. It would group the two paragraphs together as one continuing sentence.

**Comment by rodica-andronache** [comment]
Hi @terry212 ,

Thank you for contacting us. Are you using the latest version of the theme?
Also, have you tried using the <br> tag for new line in the content? Please let me know.

Regards,
Rodica

**Comment by terry212** [comment]
I just tried the tag and it works! Thank you!

**Comment by rodica-andronache** [comment]
Hi @terry212 ,

I'm really glad to hear that everything is ok now. If you like our theme and support, you can always leave us a review here https://wordpress.org/support/theme/llorix-one-lite/reviews/#new-post . It would help us a lot.

Thank you,
Rodica
