### ISSUE TITLE
Issue with featured images in latest news area

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/llorix-one-lite#104]
@rodica-andronache image doesn't fit in circle in latest update: http://prnt.sc/cqe0b2

**Comment by rodica-andronache** [comment]
@UVLabs did you test this or it was just reported by the user?

**Comment by UVLabs** [comment]
Reported and I tested myself @rodica-andronache

**Comment by claudiuvertistudio** [comment]
I have tested and seems to work well

**Comment by UVLabs** [comment]
@HardeepAsrani @Basilakis could you guys check?

**Comment by HardeepAsrani** [comment]
Can't reproduce.

**Comment by rodica-andronache** [comment]
@UVLabs I'll close this as we can't replicate. if you find out more details let me know
