### ISSUE TITLE
Add filters for the default values 

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-lite#106]
- [x] for the big title section - title

- [x] for the big title section - subtitle

- [x] for the big title section - logo

For example, you can see zerif pro. For example zerif_bigtitle_background_filter

We use this filters to be able to change the default values in child themes

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , I think we should add filters for all defaults, not only for big title. What do you think?

**Comment by cristian-ungureanu** [comment]
And not just for controls that have default options, we need this for all controls.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I added a comment here https://github.com/cristian-ungureanu/llorix-one-lite/commit/f5c49bf0c94c717eb9a8a3b0ed8ae241656f7197#comments
