### ISSUE TITLE
first contact icon in the contact section not to show

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/llorix-one-lite#113]
@rodica-andronache We have a bug in Llorix One Theme

"
there is a bug in the "Llorix One Lite" Theme (Version 0.1.20).

In File ...\sections\llorix_one_lite_contact_info_section.php on lines 68, 70, 131 and 133 it is written

<i class=fa "'

instead of

<i class="fa '

This causes the first contact icon in the contact section not to show.
"

**Comment by rodica-andronache** [comment]
this is fixed
