### ISSUE TITLE
Move the message from Frontpage settings in customize

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-lite#117]
Move this text http://prntscr.com/d5kat7 to Frontpage sections on top http://prntscr.com/d5kb4w ,
ONLY if the current page has not the frontpage template.

**Comment by cristian-ungureanu** [comment]
@rodica-andronache done

**Comment by rodica-andronache** [comment]
@cristian-ungureanu I actually realised I left some comments here https://github.com/Codeinwp/llorix-one-lite/pull/122/commits/4a66929641f1c741d2b1f1b435d20c3f9ea97983 . That's why I moved the issue to Current week :)
