### ISSUE TITLE
Add Clarina child theme in the About Llorix page

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-lite#119]
the same as Naturelle is right now

**Comment by claudiuvertistudio** [comment]
@rodica-andronache for Get Now button what link we should add?

**Comment by ineagu** [comment]
https://wordpress.org/themes/download/clarina.0.1.zip?nostats=1

**Comment by rodica-andronache** [comment]
@claudiuvertistudio  there's also need for the image http://prntscr.com/dhuk87 ,

the div shouldn't have the llorix-one-lite-tab-pane-first-half class,

for the demo page , please check the link to http://justfreethemes.com/demo?theme=Clarina
