### ISSUE TITLE
Find some troubles with the theme

### ISSUE THREAD

**Issue by Luiniux** [Codeinwp/llorix-one-lite#121]
It is my first time to use the theme,when I want to change the content in the Services Section,please tell me how to change the content which are
Lorem Ipsum

Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla nec purus feugiat, molestie ipsum et, consequat nibh. Etiam non elit dui. Nullam vel eros sit amet arcu vestibulum accumsan in in leo.

**Comment by rodica-andronache** [comment]
Hi @Luiniux ,

I'm really sorry for the long waiting time. To set up the services section, you would have to first have the Llorix Companion plugin installed https://wordpress.org/plugins/llorix-one-companion/ and go to your Dashboard -> Appearance -> Customize -> Frontpage sections -> Services section -> and there you can change/add service boxes.
You can find more details in the documentation here http://docs.themeisle.com/article/186-llorix-one-documentation or by contacting us here https://themeisle.com/contact/.

Regards,
Rodica
