### ISSUE TITLE
Remove frontpage template and the content in the frontpage

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-lite#125]
like on hestia.

Check if this affects current users

**Comment by abaicus** [comment]
Has to be made compatible with pro version and companion plugin. @rodica-andronache @cristian-ungureanu

**Comment by rodica-andronache** [comment]
@abaicus it doesn't seem to work ok here. with latest posts selected the frontpage template is shown, not the latest posts, like it is now. can you please check?
