### ISSUE TITLE
Allow tel link html in very top header

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/llorix-one-lite#129]
@rodica-andronache http://prntscr.com/dl5kad we should allow this so users on mobile can quickly call, as well as desktop

**Comment by alexcotton007** [comment]
Hello @uriahs-victor
but I do not understand the place to insert the patch

/* VERY TOP HEADER */
$llorix_one_lite_very_top_header_show = get_theme_mod( ‘llorix_one_lite_very_top_header_show’, apply_filters( ‘llorix_one_lite_very_top_header_show_filter’,0 ) );

/* If section is not disabled */
if ( isset( $llorix_one_lite_very_top_header_show ) && $llorix_one_lite_very_top_header_show != 1 ) {
?>
<div class=”very-top-header” id=”very-top-header”>
<div class=”container”>
<?php
$llorix_one_lite_very_top_header_phone = get_theme_mod( ‘llorix_one_lite_very_top_header_phone’,esc_html__( ‘(+9) 0999.500.400′,’llorix-one-lite’ ) );
$llorix_one_lite_very_top_header_phone_text = get_theme_mod( ‘llorix_one_lite_very_top_header_phone_text’,esc_html__( ‘Call us: ‘,’llorix-one-lite’ ) );

if ( ! empty( $llorix_one_lite_very_top_header_phone ) || ! empty( $llorix_one_lite_very_top_header_phone_text ) ) {
echo ‘<div class=”very-top-left”>’;
echo $llorix_one_lite_very_top_header_phone_text;
echo ‘<span>’ . esc_attr( $llorix_one_lite_very_top_header_phone ) . ‘</span>’;
echo ‘</div>’;
} elseif ( isset( $wp_customize ) ) {
echo ‘<div class=”very-top-left llorix_one_lite_only_customizer”><span></span></div>’;
}
?>

Thanks
