### ISSUE TITLE
Main page content not displayed after the last update

### ISSUE THREAD

**Issue by Sawwa7World** [Codeinwp/llorix-one-lite#134]
kindly need your help.

Regards,
Fahad

**Comment by rodica-andronache** [comment]
Hi @Sawwa7World ,

Can you please give us your site URL so we can see the issue?

Thank you,
Rodica

**Comment by rodica-andronache** [comment]
Hi @Sawwa7World ,

If you still need help with this, and if what I understood is correct, you can update the theme to the latest version 0.2.3 and use the option "Keep the old static frontpage template?" from the Advanced options panel, as mentioned here in the documentation: http://docs.themeisle.com/article/186-llorix-one-documentation#s1.

Let me know if this is helping you or if I can do anything else.

Regards,
Rodica
