### ISSUE TITLE
Ribbon section Main subtitle field invalid in Clarina child theme

### ISSUE THREAD

**Issue by Odraude83** [Codeinwp/llorix-one-lite#135]
From [Wordpress.org support forum](https://wordpress.org/support/topic/ribbon-section-field-invalid/)

Using Clarina 0.1 and Llorix one lite Version: 0.2.2
Ribbon section Main subtitle field not allowing any text

**Comment by rodica-andronache** [comment]
Hi @Odraude83 ,

We'll fix this issue in the next update. But if you want, it's a quick fix that you can do, until the update will be live. You just need to change in clarina in functions.php, replace 'clarina_sanitize_text' with 'llorix_one_lite_sanitize_text' .

Regards,
Rodica
