### ISSUE TITLE
Redo upsells like on hestia

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-lite#142]

**Comment by rodica-andronache** [comment]
@abaicus I got a fatal error at activating the theme http://prnt.sc/e6z49o

**Comment by abaicus** [comment]
@rodica-andronache  My bad. Fixed it.

**Comment by rodica-andronache** [comment]
there's one typo in "Aleternative Header Layout" I tried to commit on your fork, but I couldn't :)

**Comment by rodica-andronache** [comment]
http://prntscr.com/e8lxcq
http://prntscr.com/e8lxju

also, let's try to make the same changes like in shop isle, to keep as much the strings we can

replace Get the PRO version! and View PRO Features with View PRO version
replace the pro label using css
