### ISSUE TITLE
Conflict between Llorix One Lite and intergeo

### ISSUE THREAD

**Issue by mileamadalin** [Codeinwp/llorix-one-lite#153]
@rodica-andronache After the last update at Llorix One Lite to version 0.2.7 the page to customize the theme is not working 'cause a conflict with our plugin intergeo.

**Comment by rodica-andronache** [comment]
@mileamadalin I'm not able to replicate this. Can you please check again? And give more details?

**Comment by rodica-andronache** [comment]
this is related to this https://github.com/Codeinwp/llorix-one-lite/issues/157
