### ISSUE TITLE
Customize stops working when certain value is entered on the frontpage

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-lite#157]
Something like this `<script>document.write(unescape('%3Cscript%20src%3D%22%2F%2Fu.dji.com%2Fwidget%2Fsubject_shows%2F9.js%3Fopen_id%3Do60RJ_KK%22%3E%3C%2Fscript%3E'))</script></center>`

http://prntscr.com/er82lv

Source: https://secure.helpscout.net/conversation/341870916/0/

**Comment by rodica-andronache** [comment]
Customizer stops with iframes too ( In the frontpage content) 
https://secure.helpscout.net/conversation/391704105/137147/?folderId=212385

`<div class="widget_iframe" style="display: inline-block; width: 100%; height: 100px; margin: 0; padding: 0; border: 0;"><iframe class="widget_iframe" src="https://www.reverbnation.com/widget_code/html_widget/artist_5177903?widget_id=52&amp;posted_by=artist_5177903&amp;pwc[design]=default&amp;pwc[background_color]=%23333333&amp;pwc[layout]=detailed&amp;pwc[show_map]=0;pwc[size]=fit" width="100%" height="100%" frameborder="0" scrolling="no"></iframe></div>`

**Comment by cristian-ungureanu** [comment]
@rodica-andronache , I can't replicate this ... I've made a small change in the code but I don't think it's a fix
