### ISSUE TITLE
Can't translate all parts of front page

### ISSUE THREAD

**Issue by FitzChris** [Codeinwp/llorix-one-lite#170]
Issue was raised twice by users:

#1 https://secure.helpscout.net/conversation/364338803/133097/?folderId=212388
User reports: there are some content i couldn't translate like: section titles (services, blog, our story ...etc)
i couldn't find them in polylang strings list, and i can't add new ones.

#2 https://secure.helpscout.net/conversation/371107646/134101/?folderId=1365053
User reports: My problem is how can translate ribbons in homepage.

Don't have any images; neither site is live at the moment. Seems they can't translate a lot of the front page sections

**Comment by FitzChris** [comment]
@cristian-ungureanu User #2 came back to say he had trouble getting 2 languages on front page. Sent him the documentation and he was able to get everything working.

**Comment by rodica-andronache** [comment]
@cristian-ungureanu when you have some time, you can have a look here too. I guess it's probably something related to how the user is trying to translate , but it may be also something missing in the theme
