### ISSUE TITLE
Menu issues in RTL

### ISSUE THREAD

**Issue by HardeepAsrani** [Codeinwp/llorix-one-lite#184]
I've attached a screenshot to demonstrate the issue:

![screen shot 2017-09-24 at 10 29 43 pm](https://user-images.githubusercontent.com/2649903/30784710-1c1319dc-a178-11e7-80a7-5d6a1b5aa5fc.png)

@rodica-andronache

**Comment by rodica-andronache** [comment]
we plan to migrate all users from Llorix, Azera and Parallax to Hestia, so we don't plan to work much on this themes, unless there are things really broken :)
