### ISSUE TITLE
Option to Display Sticky posts in the latest news section

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-lite#20]

**Comment by ineagu** [comment]
more details ?

**Comment by rodica-andronache** [comment]
@ineagu right now the latest new section doesn't display the sticky posts. And some of the users want this ( not mentioned on llorix yet, but on zerif) . And I was thinking of adding an option to allow this

**Comment by ineagu** [comment]
as I have said the nr of users/impact is too small for an option. If is not
critical or requested by >10% of the users having an option doesn't make
sense. For 95+% of the users this will be just wasted time going through
the customizer.

In this situation the better alternative is to create a doc about it for
Zerif, if this is not easily possible, just add a filter in the theme and
after create a doc.

For Llorix we shouldn't bother at all.

On Mon, Apr 18, 2016 at 11:29 AM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> right now the latest new section
> doesn't display the sticky posts. And some of the users want this ( not
> mentioned on llorix yet, but on zerif) . And I was thinking of adding an
> option to allow this
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/llorix-one-lite/issues/20#issuecomment-211266757>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by ineagu** [comment]
Consider that the workaround for most of the users  it makes sense, they
can un-sticky those posts at the end.

On Mon, Apr 18, 2016 at 11:34 AM, Ionut Neagu <hi@ionutn.com> wrote:

> as I have said the nr of users/impact is too small for an option. If is
> not critical or requested by >10% of the users having an option doesn't
> make sense. For 95+% of the users this will be just wasted time going
> through the customizer.
>
> In this situation the better alternative is to create a doc about it for
> Zerif, if this is not easily possible, just add a filter in the theme and
> after create a doc.
>
> For Llorix we shouldn't bother at all.
>
> On Mon, Apr 18, 2016 at 11:29 AM, Rodica-Elena Andronache <
> notifications@github.com> wrote:
>
>> @ineagu <https://github.com/ineagu> right now the latest new section
>> doesn't display the sticky posts. And some of the users want this ( not
>> mentioned on llorix yet, but on zerif) . And I was thinking of adding an
>> option to allow this
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/Codeinwp/llorix-one-lite/issues/20#issuecomment-211266757>
>>
>
>
>
> --
> Ionut Neagu
> http://themeisle.com | http://codeinwp.com | http://ionutn.com
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com
