### ISSUE TITLE
Overlay doesn't cover the whole parallax images

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-lite#60]
When using the option "Parallax effect" in the big title section (http://prnt.sc/atnb6c) , the overlay is not covering the entire big title picture (http://prnt.sc/atnauy)

Source: https://wordpress.org/support/topic/shading-on-front-page-hero-image-off?replies=1

**Comment by rodica-andronache** [comment]
Aici am rezolvat eu adaugat din nou position relative pe care l-ai scot tu in commit-ul asta: https://github.com/Codeinwp/llorix-one-lite/commit/e990dc10a4a803891da9a72824beded01403b521

Mai stii cumva care era problema atunci, si daca poate fi rezolvata altfe?

**Comment by claudiuvertistudio** [comment]
Nu mai tin minte de ce am scos position relative. Am verificat si pare sa fie totul in regula.
