### ISSUE TITLE
[Suggestion] Blog default title

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/llorix-one-lite#63]
Ce parere ati avea daca pe pagina de blog/latest news in loc sa scriem blog default am avea : "This Theme Support a Custom Frontpage"

@s2abina @abaicus @claudiuvertistudio @rodica-andronache 

Ideea mea e ca lumea face download/preview, dar cand vede ca nu e ca in poza, renunta, nu isi mai bate capul cu setari, textul asta poate i-ar motiva putin mai mult sa incerce.

**Comment by abaicus** [comment]
Nu e rau. Adica pentru UX relativ la oamenii care nu vor sa isi bata capul cu asta e o idee buna. Macar primesc un imbold sa cerceteze.

**Comment by s2abina** [comment]
Da, cred ca ar merge sa fim chiar mai directi cu un CTA:
> Create a Custom Design for the Homepage 
sau 
> The FrontPage Design Can Be Easily Changed 
> This Theme Design May Be Easily Customized

**Comment by ineagu** [comment]
in situatia lor mie mi se pare pai to the point ce pusesem initial, vezi si
cu ceilalti

On Wed, Apr 20, 2016 at 10:54 AM, Sabina Ionescu <notifications@github.com>
wrote:

> Da, cred ca ar merge sa fim chiar mai directi cu un CTA:
>
> Create a Custom Design for the Homepage
> sau
> The FrontPage Design Can Be Easily Changed
> This Theme Design May Be Easily Customized
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/llorix-one-lite/issues/63#issuecomment-212335903>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by s2abina** [comment]
Sa inlocuim atunci:

Blog > **This Theme Supports a Custom FrontPage**

**Comment by ineagu** [comment]
ok, @rodica as pune fara traducere asta pt test :D, ce zici ?

On Thu, Apr 21, 2016 at 2:20 PM, Sabina Ionescu <notifications@github.com>
wrote:

> Sa inlocuim atunci:
>
> Blog > *This Theme Supports a Custom FrontPage*
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/llorix-one-lite/issues/63#issuecomment-212889663>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
da, facem
