### ISSUE TITLE
New screenshot here : http://themeisle.com/wordpress-themes/free/

### ISSUE THREAD

**Issue by ineagu** [Codeinwp/llorix-one-lite#66]
@claudiuvertistudio the screenshot that we have here  : http://themeisle.com/wordpress-themes/free/ for LLorix should be the same that we use on w.org since it looks better .

**Comment by rodica-andronache** [comment]
@ineagu shouldn't we also use that image on the demo maybe? The demo frontpage looks really bad in my opinion now

**Comment by ineagu** [comment]
we can

On Tue, May 17, 2016 at 3:21 PM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> shouldn't we also use that image on
> the demo maybe? The demo frontpage looks really bad in my opinion now
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/llorix-one-lite/issues/66#issuecomment-219715267>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by claudiuvertistudio** [comment]
![llorix-one-screenshot-new-themeisle](https://cloud.githubusercontent.com/assets/3263086/17553340/0261ec0a-5f0e-11e6-9b1e-fad0d126d152.png)
