### ISSUE TITLE
Open social icons in new window

### ISSUE THREAD

**Issue by rodica-andronache** [Codeinwp/llorix-one-lite#71]
@ineagu can I make this default, right?

**Comment by ineagu** [comment]
I think this is an accesibility issue, we should recommend a plugin for
that ( something like open all links in new tabs )

On Tue, May 10, 2016 at 10:05 AM, Rodica-Elena Andronache <
notifications@github.com> wrote:

> @ineagu <https://github.com/ineagu> can I make this default, right?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/Codeinwp/llorix-one-lite/issues/71>
>



-- 
Ionut Neagu
http://themeisle.com | http://codeinwp.com | http://ionutn.com

**Comment by rodica-andronache** [comment]
@Basilakis  @HardeepAsrani @UVLabs if you saw this request, could you please try to find a plugin for this, test it, and then create a doc for this?

**Comment by Basilakis** [comment]
@ineagu @rodica-andronache We have a documentation, to open links in a new tab with some JS. Not use that one?

**Comment by rodica-andronache** [comment]
@Basilakis if we have, and it's working fine, we can use that. Just let me know

**Comment by Basilakis** [comment]
http://docs.themeisle.com/article/90-how-to-open-links-in-new-tab

it is full detailed, not needed anything else I think for that one.
now, if you ask me social media icons should open by default in new window, as it is as an external link, but that is up to @ineagu if he said not, it is a not. :)

**Comment by UVLabs** [comment]
@rodica-andronache this could be closed I think
