### ISSUE TITLE
Change color for overlay for team photos

### ISSUE THREAD

**Issue by christpr1** [Codeinwp/llorix-one-lite#79]
I would like to change the orange color overlay on the invidual team photos.

**Comment by rodica-andronache** [comment]
Hi @christpr1,

You could add a custom css code like this using https://wordpress.org/plugins/advanced-css-editor/:
`.team-member:hover .member-details {background: #fff}` where you would change #fff with the color you need.

For any other support related questions, please contact us here: http://themeisle.com/contact/ . We use Github only for code subversioning , bug reporting and contribution.

Thank you for understanding,
Rodica
