### ISSUE TITLE
The code in Footer.php is not updating

### ISSUE THREAD

**Issue by Lokkuu** [Codeinwp/llorix-one-lite#83]
Howdy,

I was just inserting an image in the footer and as I tried to update it all the code got erased.
And when I tried to paste code from the backup , the same problem persists.
please help

**Comment by rodica-andronache** [comment]
Hi @Lokkuu ,

Thank you for contacting us! Could you please give us more details about this? Where exactly did you upload the image? And what is your site?

Regards,
Rodica

**Comment by Lokkuu** [comment]
@rodica-andronache 

Thanks for responding so swiftly.
My  website is http//www.mrmun.com and The attachment says it all. I was trying to edit footer . I was uploading an logo image there and once i clicked on update file . The message shown was file edited successfully but all the code of footer was gone. Even I tried to paste my backup code but the same thing happened again and again.
After all this my website is under mess. Please help.


![screen shot 2016-08-19 at 2 59 03 pm](https://cloud.githubusercontent.com/assets/6475030/17828809/a74ae8a4-66b9-11e6-89fe-b273197e8b36.png)

**Comment by rodica-andronache** [comment]
Hi @Lokkuu ,

Sorry for the late answer. I don't really understand the issue, as I was unaware that you can upload images through that editor, but only can insert code :) Can you please let me know how yo've done that, or what code did entered there?
I don't think there is an issue with the theme, rather it's something with the code entered.

Regards,
Rodica

**Comment by HardeepAsrani** [comment]
@Lokkuu That appears to be an issue with your WordPress/plugins. The theme has no control over file editor. :)

**Comment by rodica-andronache** [comment]
Hi @Lokkuu ,

As of no answer for 6 days, I will close this, but if you still have problems, please let us know here or better on our support page http://themeisle.com/support/

Thank you,
Rodica

**Comment by Lokkuu** [comment]
Hi There,
Sorry for the late reply. I was busy. I fixed that issue. Actually, the problem was from css , where I changed some code and when I pasted my old code . All came back to Normal.
Thanks to all for you support. 
I learnt a lot.

**Comment by rodica-andronache** [comment]
Hi,

I'm glad to know everything is ok now. You can always contact us on http://themeisle.com/contact/ if you have problems with our products.

Regards,
Rodica
