### ISSUE TITLE
About section stripping some tags

### ISSUE THREAD

**Issue by UVLabs** [Codeinwp/llorix-one-lite#86]
I've noticed various tags work in the preview but get stripped on save. Some properties also get stripped like inline styles of the button shown in this image: http://prnt.sc/cbw6vl

@rodica-andronache what's your say here?

**Comment by cbeckley13** [comment]
This would be a very helpful fix/addition, if possible. Thanks!

**Comment by cbeckley13** [comment]
Are there any updates on this? I need to make a decision on a new theme and must move on if this enhancement can not be done. Thanks!

**Comment by rodica-andronache** [comment]
Hi @cbeckley13 ,

Sorry for the late answer. We are working on a update for Llorix One Lite and Llorix Plus, planned to be released at the end of this week. This issue can be fixed, so I just added it to the to do list for that update.

Thank you,
Rodica

**Comment by cbeckley13** [comment]
Excellent! Thanks for the update.
