### ISSUE TITLE
Big Section Title

### ISSUE THREAD

**Issue by Lokkuu** [Codeinwp/llorix-one-lite#91]
Hi, I want to change the color of my Big Section Title so that I can match up this to my theme. But I am unable to do so. 
Please Help.

Also my css file does not have 3.10 section.

**Comment by rodica-andronache** [comment]
Hi Lokkuu,

Thank you for contacting us. We usually use github for reporting bugs or propose new features and for support related issues we recommend http://themeisle.com/contact/ so please contact us there for support issues :).
Changing colors for all the elements in the theme, is available in the PRO plugin.
Just as a simple answer , you could maybe try something like this 
`h1.intro {color: red;}`

Regards,
Rodica
